version: "3.2"
services:
  clickhouse1:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse1
    ports:
      - 9001:9000
    volumes:
      - ./:/data/
    user: root
    ulimits:
      nofile:
       soft: 262144
       hard: 262144
    environment:
      - TZ=Asia/Shanghai
  clickhouse2:
    image: yandex/clickhouse-server:1.1.54380
    container_name: clickhouse2
    ports:
      - 9002:9000
    volumes:
      - ./:/data/
    user: root
    ulimits:
      nofile:
       soft: 262144
       hard: 262144
    environment:
      - TZ=Asia/Shanghai